"""Mesh export utilities: supports .obj and .ply formats."""
from __future__ import annotations
import struct
from pathlib import Path
import numpy as np
def export_mesh(mesh: dict[str, object], path: str | Path) -> Path:
    """Export a mesh dictionary to disk.
    The ``mesh`` dict must contain:
    - ``verts``: array-like of shape (V, 3) — vertex positions
    - ``faces``: array-like of shape (F, 3) — triangle face indices
    The format is determined by the file extension (.obj or .ply).
    Defaults to OBJ for unknown extensions.
    Args:
        mesh: Dict with 'verts' and 'faces' arrays.
        path: Output file path.
    Returns:
        The resolved output path.
    """
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ext = output_path.suffix.lower()
    verts = np.asarray(mesh["verts"], dtype=np.float32)
    faces = np.asarray(mesh["faces"], dtype=np.int32)
    if ext == ".ply":
        _write_ply(verts, faces, output_path)
    else:
        _write_obj(verts, faces, output_path)
    return output_path
def _write_obj(verts: np.ndarray, faces: np.ndarray, path: Path) -> None:
    """Write an OBJ file (plain text, widely supported)."""
    lines: list[str] = ["# Generated by biomol_surface_unsup\n"]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
    for f in faces:
        # OBJ face indices are 1-based
        lines.append(f"f {f[0]+1} {f[1]+1} {f[2]+1}\n")
    path.write_text("".join(lines), encoding="utf-8")
def _write_ply(verts: np.ndarray, faces: np.ndarray, path: Path) -> None:
    """Write a binary PLY file (compact, supports per-vertex normals later)."""
    num_verts = len(verts)
    num_faces = len(faces)
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        f"element vertex {num_verts}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        f"element face {num_faces}\n"
        "property list uchar int vertex_indices\n"
        "end_header\n"
    )
    with open(path, "wb") as f:
        f.write(header.encode("ascii"))
        f.write(verts.astype(np.float32).tobytes())
        for face in faces:
            f.write(struct.pack("<B", 3))
            f.write(struct.pack("<3i", int(face[0]), int(face[1]), int(face[2])))